channels:
  - conda-forge
  - bioconda
  - intel
  - r
dependencies:
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - seaborn
  - bedops
  - bedtools
  - bcftools
  - plotly
  - scikit-learn
  - nodejs
  - pysam
  - plink
  - r-irkernel
