channels:
  - conda-forge
  - bioconda
  - intel
dependencies:
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - seaborn
  - bedops
  - bedtools
  - bcftools
  - plotly
  - scikit-learn
  - nodejs
  - pysam
  - snpeff
  -r-essentials 
  -r-base
